modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="create_weed"
version="1.0"
displayName="Create: Weed!"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Koxereq / Discord: kooerk"
description="A create addon, which adds a variety of new cannabis products for you to craft and consume"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.create_weed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



